This repository holds my dotfiles setup. It is based on [[https://github.com/nix-community/home-manager][home-manager]], a [[https://nixos.org/][Nix]]
based approach to handling all dependencies and setup. This means that all
dotfiles are actually symlinked to the nix store, and are immutable. This in
turn means I'll have to deploy changes every time I want to change something,
but I can live with it.

[[https://github.com/knl/dotskel/actions/workflows/build.yml][https://github.com/knl/dotskel/actions/workflows/build.yml/badge.svg]]

* Installation
** Command Line Tools

   Command Line Tools are needed to build various things, and bring in git.

   #+begin_src bash
     xcode-select --install
   #+end_src

** =nix=

   The new installer from Determinate Systems started forcing some DS specific
   things and leaning heavily onto flakes, that I still don't use, so we'll use
   the standard installer:

   #+begin_src bash
     tmp_conf="$(mktemp)"
     
     cat > "$tmp_conf" <<EOF
     experimental-features = nix-command flakes
     substituters = https://knl.cachix.org
     substituters = https://niv.cachix.org
     substituters = https://cache.nixos.org
     substituters = https://nix-community.cachix.org
     substituters = https://fzakaria.cachix.org
     substituters = https://devenv.cachix.org
     trusted-public-keys = knl.cachix.org-1:/iqUbqBexzvcDn5ee7Q3Kj1MBh6P9RTwEVh6hh9SDE0=
     trusted-public-keys = niv.cachix.org-1:X32PCg2e/zAm3/uD1ScqW2z/K0LtDyNV7RdaxIuLgQM=
     trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
     trusted-public-keys = nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs=
     trusted-public-keys = fzakaria.cachix.org-1:SpQviPuoJ3GnCVG40vwTp/r9y1/cbwP808SbMJ/XlGo=
     trusted-public-keys = devenv.cachix.org-1:w1cLUi8dv3hnoSPGAuibQv+f9TZLr6cv/Hm9XgU50cw=
     keep-outputs = true
     keep-derivations = true
     trusted-users = root $USER
     EOF
     
     curl -L https://nixos.org/nix/install | sh -s -- \
       --daemon \
       --yes \
       --no-channel-add \
       --nix-extra-conf-file "$tmp_conf"
     
     rm -f "$tmp_conf"
   #+end_src

** Applications

   These tools can't be installed by home-manager, because they are macOS
   applications. So, install them manually.

   - [[https://github.com/Hammerspoon/hammerspoon/releases/latest][Hammerspoon]]
   - [[https://d3jdrrl94b667u.cloudfront.net/Raycast_v1.62.1_fa62964c11720495b5c98ad1b30f32ebe5913c65_universal.dmg?response-content-disposition=attachment%3B%20filename%3DRaycast.dmg&Expires=1700563439&Signature=c87Tv1XxzDGRgIRt8zgrm0eiFO9QWxQrcYJV4qy7lyhiTtTG8J2JhTfUOsaRmJBtcE2KhtIFPnH0gG8twx2cqB2LGX5T535-UOeAVwLE7wiP-Ef9OrepvSgkZt5I6kQjWpO7tEcZXQ4j-BKJ4iV2Zph1rumTQIewTvh9ZwlgopJr6D~wK93j48dYEy5WfvKmRJbv1Jvas8Ia2shfg8NOTJhBul6huZfvY5CPJ7d7TfcXg~P8kSAyuP7jidePgcJ5VuajblyOObjkP6teR7hMSk~SNwCqxZC8rjntUd0eROM0sKs2rKiVdvh4CH8zFF3ZMq7kHOaAxfqMP7an-Vj7Xw__&Key-Pair-Id=K69CUC23G592W][Raycast]]
   - [[https://karabiner-elements.pqrs.org/][Karabiner-Elements]]
   - [[https://app-updates.agilebits.com/download/OPM7][1Password 7]]
   - [[https://www.mozilla.org/en-US/firefox/new/][Firefox]]
   - [[https://download.bjango.com/istatmenus/][iStat Menus]]
   - [[https://frankfurt.kapeli.com/downloads/v6/Dash.zip][Dash]]
   - [[https://www.postbox-inc.com/download/success-mac][Postbox]]
   - [[https://www.arqbackup.com/download/arqbackup/Arq7.pkg][Arq]]
   - [[https://apps.apple.com/ca/app/tailscale/id1475387142?mt=12][Tailscale]]
   - [[https://github.com/swiftbar/SwiftBar/releases/download/v2.0.1/SwiftBar.v2.0.1.b536.zip][SwiftBar]]
   - [[https://macbartender.com/B2/updates/B6Latest/Bartender%206.dmg][Bartender]]
   - [[https://oryx.nyc3.cdn.digitaloceanspaces.com/keymapp/keymapp-latest.dmg][Keymapp]]

** Misc

    One can't live without good fonts. I prefer Iosevka:
    [[https://github.com/be5invis/Iosevka/releases][Iosevka Term SS08]]. This font
    will be installed by home-manager.

** dotfiles

   Finally, just run the following command:

   #+begin_src bash
     nix-shell
     home-manager switch
   #+end_src
   
   Afterwards, it's just riding on the good wave of direnv and aliases:
   #+begin_src bash
     z skel
     stash; gl --rebase; unstash
     d reload
     hm switch
   #+end_src

* References

- https://hugoreeves.com/posts/2019/nix-home/
- https://github.com/ryantm/home-manager-template/blob/master/shell.nix
