This repository holds my dotfiles setup. It is based on [[https://github.com/nix-community/home-manager][home-manager]], a [[https://nixos.org/][Nix]]
based approach to handling all dependencies and setup. This means that all
dotfiles are actually symlinked to the nix store, and are immutable. This in
turn means I'll have to deploy changes every time I want to change something,
but I can live with it.

[[https://github.com/knl/dotskel/actions/workflows/build.yml][https://github.com/knl/dotskel/actions/workflows/build.yml/badge.svg]]

* Installation
** Command Line Tools

   Command Line Tools are needed to build various things, and bring in git.

   #+begin_src bash
     xcode-select --install
   #+end_src

** =nix=

   Because I neither have macOS 10.15+ nor T2 machine, I just use:
   #+begin_src bash
     sh <(curl -L https://nixos.org/nix/install)
     source "$HOME/.nix-profile/etc/profile.d/nix.sh"
   #+end_src

   Otherwise, I would've used:
   #+begin_src bash
     sh <(curl -L https://nixos.org/nix/install) --darwin-use-unencrypted-nix-store-volume
     source "$HOME/.nix-profile/etc/profile.d/nix.sh"
   #+end_src

** Applications

   These tools can't be installed by home-manager, because they are macOS
   applications. So, install them manually.

   - [[https://iterm2.com/downloads.html][iTerm2]]
   - [[https://github.com/Hammerspoon/hammerspoon/releases/latest][Hammerspoon]]
   - [[https://qsapp.com/download.php][Quicksilver]]
   - [[https://karabiner-elements.pqrs.org/][Karabiner-Elements]]
   - [[https://app-updates.agilebits.com/download/OPM7][1Password 7]]
   - [[https://www.mozilla.org/en-US/firefox/new/][Firefox]]
   - [[https://download.bjango.com/istatmenus/][iStat Menus]]
   - [[https://frankfurt.kapeli.com/downloads/v6/Dash.zip][Dash]]
   - [[https://espanso.org/install/][espanso]]

** Misc

    One can't live without good fonts. I prefer Iosevka:
    [[https://github.com/be5invis/Iosevka/releases][Iosevka Term SS08]]. This font
    will be installed by home-manager.

** dotfiles

   Finally, just run the following command:

   #+begin_src bash
     nix-shell
     home-manager switch
   #+end_src
   
   Afterwards, it's just riding on the good wave of direnv and aliases:
   #+begin_src bash
     z skel
     stash; gl --rebase; unstash
     d reload
     hm switch
   #+end_src

* References

- https://hugoreeves.com/posts/2019/nix-home/
- https://github.com/ryantm/home-manager-template/blob/master/shell.nix
