# vi:ft=toml
# name: Tempus Classic
# author: Protesilaos Stavrou (https://protesilaos.com)
# blurb: Dark theme with warm hues (WCAG AA compliant)
# license: GPLv3
# upstream: https://gitlab.com/protesilaos/tempus-themes

[colors]
# The default text color
foreground = "#aeadaf"
# The default background color
background = "#232323"

# Overrides the cell background color when the current cell is occupied by the
# cursor and the cursor style is set to Block
cursor_bg = "#aeadaf"
# Overrides the text color when the current cell is occupied by the cursor
cursor_fg = "#232323"
# Specifies the border color of the cursor when the cursor style is set to Block,
# or the color of the vertical or horizontal bar when the cursor style is set to
# Bar or Underline.
cursor_border = "#aeadaf"

# the foreground color of selected text
selection_fg = "#232323"
# the background color of selected text
selection_bg = "#aeadaf"

# The color of the scrollbar "thumb"; the portion that represents the current viewport
# scrollbar_thumb = '#222222',

# The color of the split lines between panes
# split = '#444444',

# visual_bell = '#ccd0da'

ansi = [
  '#232323',
  '#d4823d',
  '#8c9e3d',
  '#b1942b',
  '#6e9cb0',
  '#b58d88',
  '#6da280',
  '#949d9f',
] 

brights = [
  '#312e30',
  '#d0913d',
  '#96a42d',
  '#a8a030',
  '#8e9cc0',
  '#d58888',
  '#7aa880',
  '#aeadaf',
]

[metadata]
aliases = []
name = "Tempus Classic"
author = "Protesilaos Stavrou (https://protesilaos.com)"
origin_url = "https://gitlab.com/protesilaos/tempus-themes"
wezterm_version = "Always"
