# vi:ft=toml
# name: Tempus Autumn
# author: Protesilaos Stavrou (https://protesilaos.com)
# blurb: Dark theme with a palette inspired by earthly colours (WCAG AA compliant)
# license: GPLv3
# upstream: https://gitlab.com/protesilaos/tempus-themes

[colors]
# The default text color
foreground = "#a9a2a6"
# The default background color
background = "#302420"

# Overrides the cell background color when the current cell is occupied by the
# cursor and the cursor style is set to Block
cursor_bg = "#a8948a"
# Overrides the text color when the current cell is occupied by the cursor
cursor_fg = "#36302a"
# Specifies the border color of the cursor when the cursor style is set to Block,
# or the color of the vertical or horizontal bar when the cursor style is set to
# Bar or Underline.
cursor_border = "#a8948a"

# the foreground color of selected text
selection_fg = "#302420"
# the background color of selected text
selection_bg = "#a9a2a6"

# The color of the scrollbar "thumb"; the portion that represents the current viewport
scrollbar_thumb = '#a8948a',

# The color of the split lines between panes
split = '#36302a',

visual_bell = '#ba9400'

ansi = [
  '#302420',
  '#f46f55',
  '#85a400',
  '#b09640',
  '#799aca',
  '#df798e',
  '#52a885',
  '#a8948a',
] 

brights = [
  '#36302a',
  '#e27e3d',
  '#43aa7a',
  '#ba9400',
  '#958fdf',
  '#ce7dc4',
  '#2fa6b7',
  '#a9a2a6',
]

[metadata]
aliases = []
name = "Tempus Autumn"
author = "Protesilaos Stavrou (https://protesilaos.com)"
origin_url = "https://gitlab.com/protesilaos/tempus-themes"
wezterm_version = "Always"
