# vi:ft=toml
# name: Tempus Dusk
# author: Protesilaos Stavrou (https://protesilaos.com)
# blurb: Dark theme with a deep blue-ish, slightly desaturated palette (WCAG AA compliant)
# license: GPLv3
# upstream: https://gitlab.com/protesilaos/tempus-themes

[colors]
# The default text color
foreground = "#a2a8ba"
# The default background color
background = "#1f252d"

# Overrides the cell background color when the current cell is occupied by the
# cursor and the cursor style is set to Block
cursor_bg = "#a2a8ba"
# Overrides the text color when the current cell is occupied by the cursor
cursor_fg = "#1f252d"
# Specifies the border color of the cursor when the cursor style is set to Block,
# or the color of the vertical or horizontal bar when the cursor style is set to
# Bar or Underline.
cursor_border = "#a2a8ba"

# the foreground color of selected text
selection_fg = "#1f252d"
# the background color of selected text
selection_bg = "#a2a8ba"

# The color of the scrollbar "thumb"; the portion that represents the current viewport
# scrollbar_thumb = '#222222',

# The color of the split lines between panes
# split = '#444444',

# visual_bell = '#ccd0da'

ansi = [
  '#1f252d',
  '#cb8d56',
  '#8ba089',
  '#a79c46',
  '#8c9abe',
  '#b190af',
  '#8e9aba',
  '#a29899',
] 

brights = [
  '#2c3150',
  '#d39d74',
  '#80b48f',
  '#bda75a',
  '#9ca5de',
  '#c69ac6',
  '#8caeb6',
  '#a2a8ba',
]

[metadata]
aliases = []
name = "Tempus Dusk"
author = "Protesilaos Stavrou (https://protesilaos.com)"
origin_url = "https://gitlab.com/protesilaos/tempus-themes"
wezterm_version = "Always"
