# vi:ft=toml
# name: Tempus Day
# author: Protesilaos Stavrou (https://protesilaos.com)
# blurb: Light theme with warm colours (WCAG AA compliant)
# license: GPLv3
# upstream: https://gitlab.com/protesilaos/tempus-themes

[colors]
# The default text color
foreground = "#464340"
# The default background color
background = "#f8f2e5"

# Overrides the cell background color when the current cell is occupied by the
# cursor and the cursor style is set to Block
cursor_bg = "#68607d"
# Overrides the text color when the current cell is occupied by the cursor
cursor_fg = "#e7e3d7"
# Specifies the border color of the cursor when the cursor style is set to Block,
# or the color of the vertical or horizontal bar when the cursor style is set to
# Bar or Underline.
cursor_border = "#68607d"

# the foreground color of selected text
selection_fg = "#f8f2e5"
# the background color of selected text
selection_bg = "#464340"

# The color of the scrollbar "thumb"; the portion that represents the current viewport
scrollbar_thumb = '#68607d',

# The color of the split lines between panes
split = '#e7e3d7',

visual_bell = '#6f6600'

ansi = [
  '#464340',
  '#c81000',
  '#107410',
  '#806000',
  '#385dc4',
  '#b63052',
  '#007070',
  '#e7e3d7',
] 

brights = [
  '#68607d',
  '#b24000',
  '#427040',
  '#6f6600',
  '#0f64c4',
  '#8050a7',
  '#336c87',
  '#f8f2e5',
]

[metadata]
aliases = []
name = "Tempus Day"
author = "Protesilaos Stavrou (https://protesilaos.com)"
origin_url = "https://gitlab.com/protesilaos/tempus-themes"
wezterm_version = "Always"
