# vi:ft=toml
# name: Tempus Rift
# author: Protesilaos Stavrou (https://protesilaos.com)
# blurb: Dark theme with a subdued palette on the green side of the spectrum (WCAG AA compliant)
# license: GPLv3
# upstream: https://gitlab.com/protesilaos/tempus-themes

[colors]
# The default text color
foreground = "#bbbcbc"
# The default background color
background = "#162c22"

# Overrides the cell background color when the current cell is occupied by the
# cursor and the cursor style is set to Block
cursor_bg = "#bbbcbc"
# Overrides the text color when the current cell is occupied by the cursor
cursor_fg = "#162c22"
# Specifies the border color of the cursor when the cursor style is set to Block,
# or the color of the vertical or horizontal bar when the cursor style is set to
# Bar or Underline.
cursor_border = "#bbbcbc"

# the foreground color of selected text
selection_fg = "#162c22"
# the background color of selected text
selection_bg = "#bbbcbc"

# The color of the scrollbar "thumb"; the portion that represents the current viewport
# scrollbar_thumb = '#222222',

# The color of the split lines between panes
# split = '#444444',

# visual_bell = '#ccd0da'

ansi = [
  '#162c22',
  '#c19904',
  '#34b534',
  '#7fad00',
  '#30aeb0',
  '#c8954c',
  '#5fad8f',
  '#ab9aa9',
] 

brights = [
  '#283431',
  '#d2a634',
  '#6ac134',
  '#82bd00',
  '#56bdad',
  '#cca0ba',
  '#10c480',
  '#bbbcbc',
]

[metadata]
aliases = []
name = "Tempus Rift"
author = "Protesilaos Stavrou (https://protesilaos.com)"
origin_url = "https://gitlab.com/protesilaos/tempus-themes"
wezterm_version = "Always"
