# vi:ft=toml
# name: Tempus Night
# author: Protesilaos Stavrou (https://protesilaos.com)
# blurb: High contrast dark theme with bright colours (WCAG AAA compliant)
# license: GPLv3
# upstream: https://gitlab.com/protesilaos/tempus-themes

[colors]
# The default text color
foreground = "#e0e0e0"
# The default background color
background = "#1a1a1a"

# Overrides the cell background color when the current cell is occupied by the
# cursor and the cursor style is set to Block
cursor_bg = "#e0e0e0"
# Overrides the text color when the current cell is occupied by the cursor
cursor_fg = "#1a1a1a"
# Specifies the border color of the cursor when the cursor style is set to Block,
# or the color of the vertical or horizontal bar when the cursor style is set to
# Bar or Underline.
cursor_border = "#e0e0e0"

# the foreground color of selected text
selection_fg = "#1a1a1a"
# the background color of selected text
selection_bg = "#e0e0e0"

# The color of the scrollbar "thumb"; the portion that represents the current viewport
# scrollbar_thumb = '#222222',

# The color of the split lines between panes
# split = '#444444',

# visual_bell = '#ccd0da'

ansi = [
  '#1a1a1a',
  '#ff929f',
  '#5fc940',
  '#c5b300',
  '#5fb8ff',
  '#ef91df',
  '#1dc5c3',
  '#c4bdaf',
] 

brights = [
  '#242536',
  '#f69d6a',
  '#88c400',
  '#d7ae00',
  '#8cb4f0',
  '#de99f0',
  '#00ca9a',
  '#e0e0e0',
]

[metadata]
aliases = []
name = "Tempus Night"
author = "Protesilaos Stavrou (https://protesilaos.com)"
origin_url = "https://gitlab.com/protesilaos/tempus-themes"
wezterm_version = "Always"
