# vi:ft=toml
# name: Tempus Totus
# author: Protesilaos Stavrou (https://protesilaos.com)
# blurb: Light theme for prose or for coding in an open space (WCAG AAA compliant)
# license: GPLv3
# upstream: https://gitlab.com/protesilaos/tempus-themes

[colors]
# The default text color
foreground = "#4a484d"
# The default background color
background = "#ffffff"

# Overrides the cell background color when the current cell is occupied by the
# cursor and the cursor style is set to Block
cursor_bg = "#4a484d"
# Overrides the text color when the current cell is occupied by the cursor
cursor_fg = "#ffffff"
# Specifies the border color of the cursor when the cursor style is set to Block,
# or the color of the vertical or horizontal bar when the cursor style is set to
# Bar or Underline.
cursor_border = "#4a484d"

# the foreground color of selected text
selection_fg = "#ffffff"
# the background color of selected text
selection_bg = "#4a484d"

# The color of the scrollbar "thumb"; the portion that represents the current viewport
# scrollbar_thumb = '#222222',

# The color of the split lines between panes
# split = '#444444',

# visual_bell = '#ccd0da'

ansi = [
  '#4a484d',
  '#a50000',
  '#005d26',
  '#714700',
  '#1d3ccf',
  '#88267a',
  '#185570',
  '#efefef',
] 

brights = [
  '#5e4b4f',
  '#992030',
  '#4a5500',
  '#8a3600',
  '#2d45b0',
  '#700dc9',
  '#005289',
  '#ffffff',
]

[metadata]
aliases = []
name = "Tempus Totus"
author = "Protesilaos Stavrou (https://protesilaos.com)"
origin_url = "https://gitlab.com/protesilaos/tempus-themes"
wezterm_version = "Always"
