# vi:ft=toml
# name: Tempus Past
# author: Protesilaos Stavrou (https://protesilaos.com)
# blurb: Light theme inspired by old vaporwave concept art (WCAG AA compliant)
# license: GPLv3
# upstream: https://gitlab.com/protesilaos/tempus-themes

[colors]
# The default text color
foreground = "#53545b"
# The default background color
background = "#f3f2f4"

# Overrides the cell background color when the current cell is occupied by the
# cursor and the cursor style is set to Block
cursor_bg = "#80565d"
# Overrides the text color when the current cell is occupied by the cursor
cursor_fg = "#eae2de"
# Specifies the border color of the cursor when the cursor style is set to Block,
# or the color of the vertical or horizontal bar when the cursor style is set to
# Bar or Underline.
cursor_border = "#80565d"

# the foreground color of selected text
selection_fg = "#f3f2f4"
# the background color of selected text
selection_bg = "#53545b"

# The color of the scrollbar "thumb"; the portion that represents the current viewport
scrollbar_thumb = '#80565d'

# The color of the split lines between panes
split = '#eae2de'

visual_bell = '#8d554a'

ansi = [
  '#53545b',
  '#c00c50',
  '#0a7040',
  '#a6403a',
  '#1763aa',
  '#b02874',
  '#096a83',
  '#eae2de',
] 

brights = [
  '#80565d',
  '#bd3133',
  '#337243',
  '#8d554a',
  '#5559bb',
  '#b022a7',
  '#07707a',
  '#f3f2f4',
]

[metadata]
aliases = []
name = "Tempus Past"
author = "Protesilaos Stavrou (https://protesilaos.com)"
origin_url = "https://gitlab.com/protesilaos/tempus-themes"
wezterm_version = "Always"
