# vi:ft=toml
# name: Tempus Tempest
# author: Protesilaos Stavrou (https://protesilaos.com)
# blurb: A green-scale, subtle theme for late night hackers (WCAG AAA compliant)
# license: GPLv3
# upstream: https://gitlab.com/protesilaos/tempus-themes

[colors]
# The default text color
foreground = "#b6e0ca"
# The default background color
background = "#282b2b"

# Overrides the cell background color when the current cell is occupied by the
# cursor and the cursor style is set to Block
cursor_bg = "#b6e0ca"
# Overrides the text color when the current cell is occupied by the cursor
cursor_fg = "#282b2b"
# Specifies the border color of the cursor when the cursor style is set to Block,
# or the color of the vertical or horizontal bar when the cursor style is set to
# Bar or Underline.
cursor_border = "#b6e0ca"

# the foreground color of selected text
selection_fg = "#282b2b"
# the background color of selected text
selection_bg = "#b6e0ca"

# The color of the scrollbar "thumb"; the portion that represents the current viewport
# scrollbar_thumb = '#222222',

# The color of the split lines between panes
# split = '#444444',

# visual_bell = '#ccd0da'

ansi = [
  '#282b2b',
  '#cfc80a',
  '#7ad97a',
  '#bfcc4a',
  '#60d7cd',
  '#c5c4af',
  '#8bd0bf',
  '#b0c8ca',
] 

brights = [
  '#323535',
  '#d1d933',
  '#99e299',
  '#bbde4f',
  '#74e4cd',
  '#d2d4aa',
  '#9bdfc4',
  '#b6e0ca',
]

[metadata]
aliases = []
name = "Tempus Tempest"
author = "Protesilaos Stavrou (https://protesilaos.com)"
origin_url = "https://gitlab.com/protesilaos/tempus-themes"
wezterm_version = "Always"
