# vi:ft=toml
# name: Tempus Summer
# author: Protesilaos Stavrou (https://protesilaos.com)
# blurb: Dark theme with colours inspired by summer evenings by the sea (WCAG AA compliant)
# license: GPLv3
# upstream: https://gitlab.com/protesilaos/tempus-themes

[colors]
# The default text color
foreground = "#a0abae"
# The default background color
background = "#202c3d"

# Overrides the cell background color when the current cell is occupied by the
# cursor and the cursor style is set to Block
cursor_bg = "#949cbf"
# Overrides the text color when the current cell is occupied by the cursor
cursor_fg = "#39304f"
# Specifies the border color of the cursor when the cursor style is set to Block,
# or the color of the vertical or horizontal bar when the cursor style is set to
# Bar or Underline.
cursor_border = "#949cbf"

# the foreground color of selected text
selection_fg = "#202c3d"
# the background color of selected text
selection_bg = "#a0abae"

# The color of the scrollbar "thumb"; the portion that represents the current viewport
scrollbar_thumb = '#949cbf',

# The color of the split lines between panes
split = '#39304f',

visual_bell = '#be981f'

ansi = [
  '#202c3d',
  '#fe6f70',
  '#4eb075',
  '#ba9a0a',
  '#60a1e6',
  '#d285ad',
  '#3dae9f',
  '#949cbf',
] 

brights = [
  '#39304f',
  '#ec7f4f',
  '#5baf4f',
  '#be981f',
  '#8599ef',
  '#cc82d7',
  '#2aacbf',
  '#a0abae',
]

[metadata]
aliases = []
name = "Tempus Summer"
author = "Protesilaos Stavrou (https://protesilaos.com)"
origin_url = "https://gitlab.com/protesilaos/tempus-themes"
wezterm_version = "Always"
