# vi:ft=toml
# name: Tempus Dawn
# author: Protesilaos Stavrou (https://protesilaos.com)
# blurb: Light theme with a soft, slightly desaturated palette (WCAG AA compliant)
# license: GPLv3
# upstream: https://gitlab.com/protesilaos/tempus-themes

[colors]
# The default text color
foreground = "#4a4b4e"
# The default background color
background = "#eff0f2"

# Overrides the cell background color when the current cell is occupied by the
# cursor and the cursor style is set to Block
cursor_bg = "#4a4b4e"
# Overrides the text color when the current cell is occupied by the cursor
cursor_fg = "#eff0f2"
# Specifies the border color of the cursor when the cursor style is set to Block,
# or the color of the vertical or horizontal bar when the cursor style is set to
# Bar or Underline.
cursor_border = "#4a4b4e"

# the foreground color of selected text
selection_fg = "#eff0f2"
# the background color of selected text
selection_bg = "#4a4b4e"

# The color of the scrollbar "thumb"; the portion that represents the current viewport
# scrollbar_thumb = '#222222',

# The color of the split lines between panes
# split = '#444444',

# visual_bell = '#ccd0da'

ansi = [
  '#4a4b4e',
  '#a32a3a',
  '#206620',
  '#745300',
  '#4b529a',
  '#8d377e',
  '#086784',
  '#dee2e0',
] 

brights = [
  '#676364',
  '#a64822',
  '#187408',
  '#8b590a',
  '#5c59b2',
  '#8e45a8',
  '#3f649c',
  '#eff0f2',
]

[metadata]
aliases = []
name = "Tempus Dawn"
author = "Protesilaos Stavrou (https://protesilaos.com)"
origin_url = "https://gitlab.com/protesilaos/tempus-themes"
wezterm_version = "Always"
