name: Test and build
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test-and-build:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2.4.0
      - id: set_var
        run: |
            content=$(cat ./nix/sources.json)
            # the following lines are only required for multi line json
            content="${content//'%'/'%25'}"
            content="${content//$'\n'/'%0A'}"
            content="${content//$'\r'/'%0D'}"
            # end of optional handling for multi line json
            echo "::set-output name=nivSourcesJson::$content"
      - run: |
          echo "Got this HERE: $foobar"
        env:
          foobar: ${{ fromJson(steps.set_var.outputs.nivSourcesJson).nixpkgs.url }}
      - name: "Install Nix"
        uses: cachix/install-nix-action@v16
        with:
          # nix_path: ${{ format('nixpkgs={0}', fromJson(steps.set_var.outputs.nivSourcesJson).nixpkgs.url) }}
          nix_path: nixpkgs=channel:nixos-unstable
      - name: "Install Cachix"
        uses: cachix/cachix-action@v10
        with:
          name: knl
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          extraPullNames: nix-community
      # Needed because cachix is also installed by Home Manager
      # - name: "Set priority flag for Cachix 🚩"
      #   run: nix-env --set-flag priority 0 cachix
      - name: "Build and push home-manager config"
        run: |
          export NIXPKGS_ALLOW_UNFREE=1
          nix-shell --run 'home-manager build'
          readlink result | cachix push knl
