name: Test and build
on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  test-and-build:
    runs-on: macos-14
    steps:
      - name: "Free up disk space"
        run: |
          sudo rm -rf \
            "$AGENT_TOOLSDIRECTORY" \
            /opt/google/chrome \
            /opt/microsoft/msedge \
            /opt/microsoft/powershell \
            /opt/pipx \
            /usr/lib/mono \
            /usr/local/julia* \
            /usr/local/lib/android \
            /usr/local/lib/node_modules \
            /usr/local/share/chromium \
            /usr/local/share/powershell \
            /usr/share/dotnet \
            /usr/share/swift
          find /Applications/ -name "Xcode*" | sort -r | tail --lines=+2 | xargs rm -rf
          df -h /
      - uses: actions/checkout@v4
      - id: set_var
        run: |
          content=$(jq -r .nixpkgs.url <./nix/sources.json)
          echo "nivSourcesJson=$content" >> $GITHUB_ENV
      - name: "Install Nix"
        uses: cachix/install-nix-action@v30
        with:
          nix_path: ${{ format('nixpkgs={0}', env.nivSourcesJson) }}
      - name: "Install Cachix"
        uses: cachix/cachix-action@v15
        with:
          name: knl
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          extraPullNames: nix-community
      # Needed because cachix is also installed by Home Manager
      # - name: "Set priority flag for Cachix 🚩"
      #   run: nix-env --set-flag priority 0 cachix
      - name: "Build and push home-manager config"
        run: |
          export NIXPKGS_ALLOW_UNFREE=1
          nix-shell --run 'home-manager build'
          readlink result | cachix push knl
