name: Automatically update nixpkgs
on:
  # Manual override, one can start the workflow by running:
  # curl -H "Accept: application/vnd.github.everest-preview+json" \
  #  -H "Authorization: token <your-token-here>" \
  #  --request POST \
  #  --data '{"event_type": "niv-updater-nixpkgs-nudge", "client_payload": {}}' \
  #  https://api.github.com/repos/knl/dotskel/dispatches
  # https://help.github.com/en/actions/reference/events-that-trigger-workflows#external-events-repository_dispatch
  repository_dispatch:
    types: niv-updater-nixpkgs-nudge
  schedule:
    # * is a special character in YAML so you have to quote this string
    # Run every Monday at 01:17, but we use the dispatch to trigger when urgent
    - cron:  '17 01 * * 1'
jobs:
  niv-updater:
    name: 'Check for updates (weekly)'
    runs-on: ubuntu-latest
    steps:
      - name: niv-updater-action
        uses: knl/niv-updater-action@master
        with:
          whitelist: 'nixpkgs'
          keep_updating: true
          branch_prefix: 'update/'
        env:
          GITHUB_TOKEN: ${{ secrets.NIV_UPDATER_TOKEN }}

