name: Automatically update niv-managed dependencies
on:
  # Manual override, one can start the workflow by running:
  # curl -H "Accept: application/vnd.github.everest-preview+json" \
  #  -H "Authorization: token <your-token-here>" \
  #  --request POST \
  #  --data '{"event_type": "niv-updater-nudge", "client_payload": {}}' \
  #  https://api.github.com/repos/knl/dotskel/dispatches
  # https://help.github.com/en/actions/reference/events-that-trigger-workflows#external-events-repository_dispatch
  repository_dispatch:
    types: niv-updater-nudge
  schedule:
    # * is a special character in YAML so you have to quote this string
    # Run every Tuesday at 06:30, but we use the dispatch to trigger when urgent
    # This used to run every day, but that is way too many changes...
    - cron:  '30 6 * * 2'
jobs:
  niv-updater:
    name: 'Check for updates (daily)'
    runs-on: ubuntu-latest
    steps:
      - name: niv-updater-action
        uses: knl/niv-updater-action@main
        with:
          blacklist: 'nixpkgs'
          keep_updating: true
          branch_prefix: 'update/'
          # Last good version that doesn't require rebuilding the world
          niv_version: 'af958e8057f345ee1aca714c1247ef3ba1c15f5e'
        env:
          GITHUB_TOKEN: ${{ secrets.NIV_UPDATER_TOKEN }}
